# SPDX-License-Identifier: GPL-2.0
# PDM Bus - Standard Linux bus_type implementation

# Only compile if new bus is enabled
pdm_core-$(CONFIG_PDM_NEW_BUS) += pdm-core/bus/pdm_bus.o
pdm_core-$(CONFIG_PDM_NEW_BUS) += pdm-core/bus/pdm_device.o
pdm_core-$(CONFIG_PDM_NEW_BUS) += pdm-core/bus/pdm_bus_controller.o
