# ==============================================================================
# Kconfig Configuration Loader for LPF
# ==============================================================================
# This module provides clean separation between configuration management and
# build logic, inspired by Kconfig-driven build systems.
#
# Design principles:
#   - Configuration management is isolated from build logic
#   - Single source of truth: .config file
#   - Fail-fast validation with clear error messages
#   - Compatible with both standalone and Buildroot workflows
#
# Usage:
#   include(scripts/cmake/kconfig_loader.cmake)
#   kconfig_load()
#
# Public functions:
#   kconfig_load()          - Load .config and setup build environment
#   kconfig_print_summary() - Print configuration summary for debugging
# ==============================================================================

# Guard against multiple inclusion
if(DEFINED __KCONFIG_LOADER_INCLUDED)
    return()
endif()
set(__KCONFIG_LOADER_INCLUDED TRUE)

# ==============================================================================
# Private helper functions
# ==============================================================================

# Parse a single CONFIG line and set CMake variable
function(_kconfig_parse_line line)
    # Skip empty lines and pure comments
    if(NOT line OR line MATCHES "^[ \t]*$")
        return()
    endif()

    # Handle: CONFIG_XXX=value
    if(line MATCHES "^CONFIG_([A-Za-z0-9_]+)=(.*)$")
        set(config_name ${CMAKE_MATCH_1})
        set(config_value ${CMAKE_MATCH_2})

        # Remove quotes from string values
        string(REGEX REPLACE "^\"(.*)\"$" "\\1" config_value "${config_value}")

        # Convert y/n to ON/OFF for CMake boolean logic
        if(config_value STREQUAL "y")
            set(config_value ON)
        elseif(config_value STREQUAL "n")
            set(config_value OFF)
        endif()

        # Export to parent scope (caller's scope)
        set(CONFIG_${config_name} ${config_value} PARENT_SCOPE)

    # Handle: # CONFIG_XXX is not set
    elseif(line MATCHES "^#[ \t]*CONFIG_([A-Za-z0-9_]+)[ \t]+is[ \t]+not[ \t]+set")
        set(config_name ${CMAKE_MATCH_1})
        set(CONFIG_${config_name} OFF PARENT_SCOPE)
    endif()
endfunction()

# Validate required configuration symbols
function(_kconfig_validate)
    set(validation_failed FALSE)

    # Check critical configuration symbols
    if(NOT DEFINED CONFIG_PROJECT_NAME)
        if(NOT BUILD_QUIET_MODE)
            message(WARNING "CONFIG_PROJECT_NAME not defined in .config")
        endif()
        set(validation_failed TRUE)
    endif()

    if(NOT DEFINED CONFIG_PROJECT_VERSION)
        if(NOT BUILD_QUIET_MODE)
            message(WARNING "CONFIG_PROJECT_VERSION not defined in .config")
        endif()
    endif()

    # Validate architecture is set
    if(NOT CONFIG_ARCH_X86_64 AND
       NOT CONFIG_ARCH_ARM64 AND
       NOT CONFIG_ARCH_ARM32 AND
       NOT CONFIG_ARCH_RISCV64)
        if(NOT BUILD_QUIET_MODE)
            message(WARNING "No architecture selected (CONFIG_ARCH_*)")
        endif()
        set(validation_failed TRUE)
    endif()

    if(validation_failed AND NOT BUILD_QUIET_MODE)
        message(WARNING "Configuration validation found issues - proceeding with caution")
    endif()
endfunction()

# Setup compiler auto-include for gen_autoconf.h
function(_kconfig_setup_autoinclude autoconf_h)
    if(NOT EXISTS "${autoconf_h}")
        message(WARNING "Configuration header not found: ${autoconf_h}")
        message(WARNING "Expected to be generated by Makefile")
        return()
    endif()

    # Auto-include gen_autoconf.h in all source files
    add_compile_options(-include "${autoconf_h}")

    # Add include directory for generated headers
    get_filename_component(autoconf_dir "${autoconf_h}" DIRECTORY)
    include_directories("${autoconf_dir}/..")

    # Only print in verbose mode
    if(NOT BUILD_QUIET_MODE)
        message(STATUS "Kconfig: Auto-including ${autoconf_h}")
    endif()
endfunction()

# ==============================================================================
# Public API
# ==============================================================================

# Main function: Load Kconfig configuration and setup build environment
function(kconfig_load)
    # Check if already loaded
    if(KCONFIG_LOADED)
        message(STATUS "Kconfig: Configuration already loaded")
        return()
    endif()

    # -------------------------------------------------------------------
    # Step 1: Locate configuration file
    # -------------------------------------------------------------------
    if(DEFINED CONFIG_FILE)
        set(config_file "${CONFIG_FILE}")
    else()
        set(config_file "${CMAKE_SOURCE_DIR}/.config")
    endif()

    if(NOT EXISTS "${config_file}")
        message(FATAL_ERROR
            "\n"
            "========================================================================\n"
            "  ERROR: Kconfig configuration file not found!\n"
            "========================================================================\n"
            "  Expected: ${config_file}\n"
            "\n"
            "  Please run a configuration command first:\n"
            "    make menuconfig              - Interactive configuration\n"
            "    make <board>_defconfig       - Load board configuration\n"
            "    make list                    - List available configurations\n"
            "========================================================================\n")
    endif()

    message(STATUS "Kconfig: Loading configuration from ${config_file}")

    # -------------------------------------------------------------------
    # Step 2: Parse configuration file
    # -------------------------------------------------------------------
    # -------------------------------------------------------------------
    # Step 2: Parse .config file
    # -------------------------------------------------------------------
    file(STRINGS "${config_file}" config_lines)
    set(config_count 0)

    foreach(line IN LISTS config_lines)
        _kconfig_parse_line("${line}")

        # Count processed symbols
        if(line MATCHES "^CONFIG_")
            math(EXPR config_count "${config_count} + 1")
        endif()
    endforeach()

    # Export all CONFIG_* variables to parent scope (CMakeLists.txt)
    get_cmake_property(all_vars VARIABLES)
    foreach(var ${all_vars})
        if(var MATCHES "^CONFIG_")
            set(${var} ${${var}} PARENT_SCOPE)
        endif()
    endforeach()

    # Only print in verbose mode
    if(NOT BUILD_QUIET_MODE)
        message(STATUS "Kconfig: Loaded ${config_count} configuration symbols")
    endif()

    # -------------------------------------------------------------------
    # Step 3: Validate configuration
    # -------------------------------------------------------------------
    _kconfig_validate()

    # -------------------------------------------------------------------
    # Step 4: Setup gen_autoconf.h auto-include
    # -------------------------------------------------------------------
    if(DEFINED AUTOCONF_H)
        set(autoconf_h "${AUTOCONF_H}")
    else()
        set(autoconf_h "${CMAKE_BINARY_DIR}/include/generated/gen_autoconf.h")
    endif()

    _kconfig_setup_autoinclude("${autoconf_h}")

    # -------------------------------------------------------------------
    # Step 5: Export metadata to parent scope
    # -------------------------------------------------------------------
    set(KCONFIG_LOADED TRUE PARENT_SCOPE)
    set(KCONFIG_FILE "${config_file}" PARENT_SCOPE)
    set(KCONFIG_AUTOCONF_H "${autoconf_h}" PARENT_SCOPE)
    set(KCONFIG_SYMBOL_COUNT ${config_count} PARENT_SCOPE)

    # Only print success message in verbose mode
    if(NOT BUILD_QUIET_MODE)
        message(STATUS "Kconfig: Configuration loaded successfully")
    endif()
endfunction()

# Print configuration summary for debugging
function(kconfig_print_summary)
    if(NOT KCONFIG_LOADED)
        message(WARNING "Kconfig not loaded yet - call kconfig_load() first")
        return()
    endif()

    message(STATUS "")
    message(STATUS "========================================================================")
    message(STATUS "Kconfig Configuration Summary")
    message(STATUS "========================================================================")
    message(STATUS "Configuration file: ${KCONFIG_FILE}")
    message(STATUS "Autoconf header:    ${KCONFIG_AUTOCONF_H}")
    message(STATUS "Symbol count:       ${KCONFIG_SYMBOL_COUNT}")
    message(STATUS "")
    message(STATUS "Key configuration:")

    # Print important configuration variables
    set(important_configs
        PROJECT_NAME
        PROJECT_VERSION
        LINUX_ONLY
        BUILD_TYPE
        ARCH_X86_64
        ARCH_ARM64
        ARCH_ARM32
        ARCH_RISCV64
        OS_LINUX
        PRODUCT_FRAMEWORK
        PRODUCT_SAMPLE
        OSAL
        LPF_PERIPHERAL_RUNTIME
        PDI
        ACONFIG
    )

    foreach(config ${important_configs})
        if(DEFINED CONFIG_${config})
            set(value ${CONFIG_${config}})
            # Format boolean values
            if(value STREQUAL "ON" OR value STREQUAL "OFF")
                string(LENGTH "${config}" config_len)
                math(EXPR padding "24 - ${config_len}")
                string(REPEAT " " ${padding} spaces)
                message(STATUS "  CONFIG_${config}${spaces}: ${value}")
            else()
                string(LENGTH "${config}" config_len)
                math(EXPR padding "24 - ${config_len}")
                string(REPEAT " " ${padding} spaces)
                message(STATUS "  CONFIG_${config}${spaces}: ${value}")
            endif()
        endif()
    endforeach()

    message(STATUS "========================================================================")
    message(STATUS "")
endfunction()

# Get a CONFIG variable with default value
function(kconfig_get var_name default_value result_var)
    if(DEFINED CONFIG_${var_name})
        set(${result_var} ${CONFIG_${var_name}} PARENT_SCOPE)
    else()
        set(${result_var} ${default_value} PARENT_SCOPE)
    endif()
endfunction()

# Check if a feature is enabled (ON/y)
function(kconfig_is_enabled var_name result_var)
    if(DEFINED CONFIG_${var_name})
        if(CONFIG_${var_name})
            set(${result_var} TRUE PARENT_SCOPE)
        else()
            set(${result_var} FALSE PARENT_SCOPE)
        endif()
    else()
        set(${result_var} FALSE PARENT_SCOPE)
    endif()
endfunction()
