# SPDX-License-Identifier: GPL-2.0

lpf_core-$(CONFIG_LPF_RUNTIME) += lpf-runtime/runtime/lpf_runtime.o
lpf_core-$(CONFIG_LPF_RUNTIME) += lpf-runtime/runtime/lpf_runtime_config.o
lpf_core-$(CONFIG_LPF_RUNTIME) += lpf-runtime/runtime/lpf_runtime_entry_start.o
