# SPDX-License-Identifier: GPL-2.0

# Object list exported for kernel modules that consume PCONFIG internally.
ESMW_PCONFIG_OBJS :=

ifeq ($(CONFIG_PCONFIG),y)
ESMW_PCONFIG_OBJS += pconfig/src/pconfig_api.o
endif
