# SPDX-License-Identifier: GPL-2.0

lpf_core-y += lpf-core/compat/lpf_compat_gpio.o
lpf_core-y += lpf-core/compat/lpf_compat_pwm.o
lpf_core-y += lpf-core/compat/lpf_compat_i2c.o
lpf_core-y += lpf-core/compat/lpf_compat_spi.o
lpf_core-y += lpf-core/compat/lpf_compat_can.o
lpf_core-y += lpf-core/compat/lpf_compat_serial.o
