# SPDX-License-Identifier: GPL-2.0

lpf_runtime-y += lpf-runtime/hw/core/lpf_hw.o
lpf_runtime-y += lpf-runtime/hw/core/lpf_hw_builtin_start.o
lpf_runtime-$(CONFIG_LPF_HW_CAN) += lpf-runtime/hw/can/lpf_hw_transport_can.o
lpf_runtime-$(CONFIG_LPF_HW_UART) += lpf-runtime/hw/uart/lpf_hw_transport_uart.o
lpf_runtime-$(CONFIG_LPF_HW_GPIO) += lpf-runtime/hw/gpio/lpf_hw_gpio.o
lpf_runtime-$(CONFIG_LPF_HW_PWM) += lpf-runtime/hw/pwm/lpf_hw_pwm.o
lpf_runtime-$(CONFIG_LPF_HW_I2C) += lpf-runtime/hw/i2c/lpf_hw_bus_i2c.o
lpf_runtime-$(CONFIG_LPF_HW_SPI) += lpf-runtime/hw/spi/lpf_hw_bus_spi.o
lpf_runtime-y += lpf-runtime/hw/core/lpf_hw_builtin_end.o
