# CCM Collector default configuration

# Enable all core modules
CONFIG_OSAL=y
CONFIG_OS_LINUX=y
CONFIG_ARCH_ARM64=y
CONFIG_OSAL_BUILD_SHARED=y
CONFIG_OSAL_IPC=y
CONFIG_OSAL_FILE=y
CONFIG_OSAL_THREAD=y
CONFIG_OSAL_NETWORK=y
CONFIG_OSAL_SIGNAL=y

CONFIG_HAL=y
CONFIG_PLATFORM_GENERIC_LINUX=y
CONFIG_HAL_BUILD_SHARED=y
CONFIG_HAL_CAN=y
CONFIG_HAL_UART=y
CONFIG_HAL_I2C=y
CONFIG_HAL_SPI=y
CONFIG_HAL_GPIO=y
CONFIG_HAL_WATCHDOG=y

CONFIG_PCL=y
CONFIG_PCL_PLATFORM_TI_AM625=y
CONFIG_PCL_PRODUCT_H200_100P=y
CONFIG_PCL_BUILD_SHARED=y

CONFIG_PDL=y
CONFIG_PDL_BUILD_SHARED=y
CONFIG_PDL_SATELLITE_SUPPORT=y
CONFIG_PDL_BMC_SUPPORT=y
CONFIG_PDL_MCU_SUPPORT=y
CONFIG_PDL_WATCHDOG_SUPPORT=y

CONFIG_ACL=y
CONFIG_ACL_BUILD_SHARED=y
CONFIG_ACL_MAX_DEVICES=64
