// SPDX-License-Identifier: GPL-2.0

#ifndef PDM_COMPAT_FEATURES_H
#define PDM_COMPAT_FEATURES_H

#include <linux/version.h>

#define PDM_KERNEL_MIN_VERSION KERNEL_VERSION(5, 10, 0)

#if LINUX_VERSION_CODE < PDM_KERNEL_MIN_VERSION
#error "PDM supports Linux kernel 5.10 or newer; extend pdm_compat before building older kernels"
#endif

#define PDM_KERNEL_HAS_PROC_OPS \
	(LINUX_VERSION_CODE >= KERNEL_VERSION(5, 6, 0))
#define PDM_KERNEL_HAS_SYSFS_EMIT \
	(LINUX_VERSION_CODE >= KERNEL_VERSION(5, 10, 0))
#define PDM_KERNEL_HAS_SOCKADDR_UNSIZED \
	(LINUX_VERSION_CODE >= KERNEL_VERSION(7, 0, 0))
#define PDM_KERNEL_HAS_VOID_I2C_REMOVE \
	(LINUX_VERSION_CODE >= KERNEL_VERSION(6, 1, 0))
#define PDM_KERNEL_HAS_I2C_PROBE_ONE_ARG \
	(LINUX_VERSION_CODE >= KERNEL_VERSION(6, 3, 0))
#define PDM_KERNEL_HAS_VOID_SPI_REMOVE \
	(LINUX_VERSION_CODE >= KERNEL_VERSION(6, 1, 0))

#endif /* PDM_COMPAT_FEATURES_H */
