# =============================================================================
# CCM apps 构建配置
# =============================================================================

# 所有应用子目录
subdir-y += ccm_supervisor/
subdir-y += ccm_logger/
subdir-y += ccm_comm/
subdir-y += ccm_collector/
subdir-y += ccm_health/
