# SPDX-License-Identifier: GPL-2.0

lpf_core-$(CONFIG_LPF_LED_SERVICE) += lpf-runtime/peripheral/led/lpf_led_config_driver.o
lpf_core-$(CONFIG_LPF_LED_SERVICE) += lpf-runtime/peripheral/led/lpf_led_service.o
lpf_core-$(CONFIG_LPF_LED_SERVICE) += lpf-runtime/peripheral/led/lpf_led_gpio.o
lpf_core-$(CONFIG_LPF_LED_SERVICE) += lpf-runtime/peripheral/led/lpf_led_pwm.o
lpf_core-$(CONFIG_LPF_LED_SERVICE) += lpf-runtime/peripheral/led/lpf_led_chrdev.o
lpf_core-$(CONFIG_LPF_LED_SERVICE) += lpf-runtime/peripheral/led/lpf_led_proc.o
