# SPDX-License-Identifier: GPL-2.0

lpf_runtime-$(CONFIG_LPF_LED_SERVICE) += lpf-runtime/peripheral/led/lpf_led_config_mapper.o
lpf_runtime-$(CONFIG_LPF_LED_SERVICE) += lpf-runtime/peripheral/led/lpf_led_service.o
lpf_runtime-$(CONFIG_LPF_LED_SERVICE) += lpf-runtime/peripheral/led/lpf_led_chrdev.o
lpf_runtime-$(CONFIG_LPF_LED_SERVICE) += lpf-runtime/peripheral/led/lpf_led_proc.o
