# SPDX-License-Identifier: GPL-2.0

lpf_core-$(CONFIG_LPF_RUNTIME) += lpf-core/hw/core/lpf_hw.o
lpf_core-$(CONFIG_LPF_RUNTIME) += lpf-core/hw/core/lpf_hw_builtin_start.o
lpf_core-$(CONFIG_LPF_HW_CAN) += lpf-core/hw/can/lpf_hw_can.o
lpf_core-$(CONFIG_LPF_HW_UART) += lpf-core/hw/uart/lpf_hw_uart.o
lpf_core-$(CONFIG_LPF_HW_GPIO) += lpf-core/hw/gpio/lpf_hw_gpio.o
lpf_core-$(CONFIG_LPF_HW_PWM) += lpf-core/hw/pwm/lpf_hw_pwm.o
lpf_core-$(CONFIG_LPF_HW_I2C) += lpf-core/hw/i2c/lpf_hw_i2c.o
lpf_core-$(CONFIG_LPF_HW_SPI) += lpf-core/hw/spi/lpf_hw_spi.o
lpf_core-$(CONFIG_LPF_RUNTIME) += lpf-core/hw/core/lpf_hw_builtin_end.o
