# SPDX-License-Identifier: GPL-2.0

lpf_core-y := lpf-core/core/lpf_core.o
lpf_core-y += lpf-core/core/lpf_chrdev.o
lpf_core-y += lpf-core/core/lpf_ctl.o
lpf_core-y += lpf-core/core/lpf_debugfs.o
lpf_core-y += lpf-core/core/lpf_proc.o
lpf_core-y += lpf-core/core/lpf_sysfs.o
