# SPDX-License-Identifier: GPL-2.0

lpf_core-y += lpf-runtime/config/src/lpf_config_api.o
lpf_core-y += lpf-runtime/config/src/lpf_config_backend.o
lpf_core-y += lpf-runtime/config/src/lpf_config_dt_backend.o
lpf_core-y += lpf-runtime/config/src/lpf_config_dt_parser.o
lpf_core-y += lpf-runtime/config/src/lpf_config_static_backend.o
lpf_core-y += lpf-runtime/config/src/lpf_config_normalizer.o
lpf_core-y += lpf-runtime/config/src/lpf_config_validator.o

lpf_configs-y += lpf-runtime/config/configs/lpf_config_configs.o
lpf_configs-$(CONFIG_LPF_CONFIG_KERNEL_X86_MODULES) += lpf-runtime/config/configs/kernel/x86_modules/lpf_config_kernel_x86_modules_v1.o
lpf_configs-$(CONFIG_LPF_CONFIG_KERNEL_X86_MOCK_MODULES) += lpf-runtime/config/configs/kernel/x86_mock_modules/lpf_config_kernel_x86_mock_modules_v1.o
