# SPDX-License-Identifier: GPL-2.0

lpf_runtime-$(CONFIG_LPF_MCU_SERVICE) += lpf-runtime/peripheral/mcu/lpf_mcu_config_mapper.o
lpf_runtime-$(CONFIG_LPF_MCU_SERVICE) += lpf-runtime/peripheral/mcu/lpf_mcu_service.o
lpf_runtime-$(CONFIG_LPF_MCU_SERVICE) += lpf-runtime/peripheral/mcu/lpf_mcu_chrdev.o
lpf_runtime-$(CONFIG_LPF_MCU_SERVICE) += lpf-runtime/peripheral/mcu/lpf_mcu_proc.o
